### ISSUE TITLE
Care with naming convention

### ISSUE THREAD

**Issue by dbuenor** [Guillenxito/CalculatorService#4]
Usually for a function, you ll need to use PascalCase to name your functions, and u have to use it along all your code.

In this case, it would be more suitable to name the function as "JournalExists" for example. And in the previous function, u should name "Sqrt". Even when its a abbreviation, u should use the same naming convention.

https://github.com/Guillenxito/CalculatorService/blob/c5cccc55b847dee18d43d4c25df1b600653bd249/CalculatorS/Controllers/CalculatorSController.cs#L299

**Comment by Guillenxito** [comment]
The name of the functions has been **modified** to _PascalCase_.
