### ISSUE TITLE
Change bool to void. The function only save the journal, not return nothing

### ISSUE THREAD

**Issue by dveraaas** [Guillenxito/CalculatorService#9]
https://github.com/Guillenxito/CalculatorService/blob/120b46585117daf7e70850c2afb163457b36be37/CalculatorS/Models/Journal.cs#L19

**Comment by Guillenxito** [comment]
The function _SaveJournal_ have been modified to return **nothing** "and check if the directory '_Tracking_' exist, if dont, i will create it.
